export default {
  SET_TASK_LIST: 'SET_TASK_LIST',
  SET_IS_FETCHING: 'SET_IS_FETCHING',
  FETCHING_SUCCESS: 'FETCHING_SUCCESS',
  ERROR: 'ERROR',
  //sagas types
  GET_LIST: 'GET_LIST',
  DELETE_TASK: 'DELETE_TASK',
  EDIT_TASK: 'EDIT_TASK',
  CREATE_TASK: 'CREATE_TASK',
}
